### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by dchilkur** [Netcentric/access-control-validator#3]
Really like the tool, great work 👍 

**Simple Test Case for Delete**
```
#This is sample test config  for base ACLs

- variables:
    - wwwRoot: /content/www

- tests:

    - apac-wems:

            - path: ${wwwRoot}
              actions: delete
              permission: deny
```
**Response**
```
{
file: "/apps/netcentric/acvalidator-examples/tests/content-authors/test.yaml",
okResults: 1,
okPercentage: 100,
ok: true,
results: [
{
authorizable: "apac-wems",
test: "Page Delete Test",
params: " path: /content/www, isSimulate:false isSimulateSuccess: false",
error: "testpage: /content/www is not existing in repository!",
ok: true
}
]
}
```
This seems to stem from the following,  dont seem to be set this var?
```
		if(!this.isTestPageExisting){
			this.errorMessage = "testpage: " + path + " is not existing in repository!";
		}
```
